name: TelegramTextureChat
options:
  minimumXcodeGenVersion: 2.38.0
settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
packages:
  Texture:
    url: https://github.com/dychanny/texture-SPM
    from: 1.0.0
targets:
  TelegramTextureChatApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: App/TelegramTextureChatApp
        excludes:
          - Resources
      - path: Sources/TelegramTextureChat
    resources:
      - path: App/TelegramTextureChatApp/Resources
    info:
      path: App/TelegramTextureChatApp/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.dychanny.telegramtexturechat
        PRODUCT_NAME: TelegramTextureChat
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
    dependencies:
      - package: Texture
        product: Texture
schemes:
  TelegramTextureChat:
    build:
      targets:
        TelegramTextureChatApp: all
    run:
      config: Debug
